set -gq allow-passthrough on
set -g extended-keys on
set -g extended-keys-format csi-u

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
